CREATE PROCEDURE [dbo].[AtualizarCliente]
	@Id INT,
    @Nome VARCHAR (MAX),
	@Cpf VARCHAR (MAX) = NULL,
	@Endereco VARCHAR (MAX) = NULL,
	@Email VARCHAR (MAX) = NULL,
	@DataNascimento DATETIME = NULL,
	@Profissao VARCHAR (MAX) = NULL,
	@QuemIndicou VARCHAR (MAX) = NULL,
	@ComoConheceu INT,
	@PraticaAtividade VARCHAR (MAX) = NULL,
	@Medicacao VARCHAR (MAX) = NULL,
	@Riscos INT,
	@Doenca VARCHAR (MAX) = NULL,
	@Dor VARCHAR (MAX) = NULL,
	@Objetivo VARCHAR (MAX) = NULL,
	@ExamesComplementares VARCHAR (MAX) = NULL,
	@Observacao VARCHAR (MAX) = NULL,
	@Pes INT,
	@Joelhos INT,
	@Pelve INT,
	@Coluna INT,
	@Ombros INT,
	@Cabeca INT
AS
	UPDATE Clientes SET Nome = @Nome, 
	Cpf = @Cpf,
	Endereco = @Endereco,
	Email = @Email,
	DataNascimento = @DataNascimento,
	Profissao = @Profissao,
	QuemIndicou = @QuemIndicou,
	ComoConheceu = @ComoConheceu,
	PraticaAtividade = @PraticaAtividade,
	Medicacao = @Medicacao,
	Riscos = @Riscos,
	Doenca = @Doenca,
	Dor = @Dor,
	Objetivo = @Objetivo,
	ExamesComplementares = @ExamesComplementares,
	Observacao = @Observacao,
	Pes = @Pes,
	Joelhos = @Joelhos,
	Pelve = @Pelve,
	Coluna = @Coluna,
	Ombros = @Ombros,
	Cabeca = @Cabeca
	WHERE Id = @Id
