CREATE PROCEDURE [dbo].[InserirCliente]
	@Id INT OUTPUT,
    @Nome VARCHAR (MAX),
	@Cpf VARCHAR (MAX) = NULL,
	@Endereco VARCHAR (MAX) = NULL,
	@Email VARCHAR (MAX) = NULL,
	@DataNascimento DATETIME = NULL,
	@Profissao VARCHAR (MAX) = NULL,
	@QuemIndicou VARCHAR (MAX) = NULL,
	@ComoConheceu INT,
	@PraticaAtividade VARCHAR (MAX) = NULL,
	@Medicacao VARCHAR (MAX) = NULL,
	@Riscos INT,
	@Doenca VARCHAR (MAX) = NULL,
	@Dor VARCHAR (MAX) = NULL,
	@Objetivo VARCHAR (MAX) = NULL,
	@ExamesComplementares VARCHAR (MAX) = NULL,
	@Observacao VARCHAR (MAX) = NULL,
	@Pes INT,
	@Joelhos INT,
	@Pelve INT,
	@Coluna INT,
	@Ombros INT,
	@Cabeca INT
AS
BEGIN
	INSERT INTO Clientes 
	(			
	Nome,
	Cpf,			
	Endereco,			
	Email,			
	DataNascimento,	
	Profissao,		
	QuemIndicou,		
	ComoConheceu,		
	PraticaAtividade,	
	Medicacao,			
	Riscos,		
	Doenca,		
	Dor,			
	Objetivo,			
	ExamesComplementares,
	Observacao,	
	Pes,			
	Joelhos,			
	Pelve,			
	Coluna,		
	Ombros,		
	Cabeca 			
	) 
	VALUES 
	(@Nome,	
	@Cpf,		
	@Endereco,			
	@Email,		
	@DataNascimento,	
	@Profissao,	
	@QuemIndicou,	
	@ComoConheceu,	
	@PraticaAtividade, 	
	@Medicacao,	
	@Riscos,	
	@Doenca,		
	@Dor,		
	@Objetivo,		
	@ExamesComplementares,
	@Observacao,	
	@Pes,		
	@Joelhos,		
	@Pelve,		
	@Coluna,			
	@Ombros,			
	@Cabeca);	

	SET @Id = SCOPE_IDENTITY();
END
